name: Rust

on:
  push:
    branches: [main]
    paths: ['rust/**', 'test-vectors/**', '.github/workflows/rust.yml']
  pull_request:
    paths: ['rust/**', 'test-vectors/**', '.github/workflows/rust.yml']

permissions:
  contents: read

defaults:
  run:
    working-directory: rust

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo build --all-features
      - run: cargo test --all-features
      - run: cargo build --no-default-features
      - run: cargo build --no-default-features --features lz4
      - run: cargo build --no-default-features --features zstd
      - run: cargo build --no-default-features --features deflate

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: '1.70'
      - run: cargo build --all-features
      - run: cargo build --no-default-features --features lz4,zstd,deflate

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy --all-features --all-targets -- -D warnings
      - run: cargo clippy --no-default-features --features lz4,zstd,deflate -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt -- --check
